<template>
  <div class="loading" v-if="on">

    <div class="loadingio-spinner-spinner-ce8pfm4ddfb">
      <div class="ldio-eeii88l764">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>

    <div class="loading-message">
      {{ labels[messageLang || defaultLang] }}
    </div>
  </div>
</template>

<script>
import basemixin from '../mixins/basemixin'
import langmixin from '../mixins/langmixin'

export default {
  mixins: [basemixin, langmixin],
  data() {
    return {
      on: true,
      defaultLang: 'LOADING-LABEL',
      messageLang: '',
      loadingTag: 'loading',
      loadingMessageTag: 'loading-message'
    };
  },
  mounted() {
    this.$app.on(this.loadingTag, this.loading, this.loadingCallback)
    this.$app.on(this.loadingMessageTag, this.loadingMessage, this.loadingMessageCallback);
  },
  unmounted() {
    this.removeListener({ listener: this.loadingTag });
    this.removeListener({ listener: this.loadingMessageTag });
  },
  methods: {
    loading(arg = { on: false, message: '' }) {
      this.on = arg.on;
      if (!this.on) this.messageLang = '';
    },
    loadingMessage(arg = { message: '' }) {
      if (!this.on) return;
      if (!this.labels[arg.message]) return;
      this.messageLang = arg.message;
    },
    loadingCallback(err, pid) {
      if (err) return console.error(err);
      this.addListener({ listener: this.loadingTag, pid: pid });
    },
    loadingMessageCallback(err, pid) {
      if (err) return console.error(err);
      this.addListener({ listener: this.loadingMessageTag, pid: pid });
    }
  }
}
</script>

<style lang="scss" scoped>
.loading {
  position: fixed;
  z-index: 5;
  width: 100%;
  height: 100%;
  cursor: progress;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  background: rgba($color: #000000, $alpha: 0.5);
}

@keyframes ldio-eeii88l764 {
  0% { opacity: 1 }
  100% { opacity: 0 }
}
.ldio-eeii88l764 div {
  left: 115.64999999999999px;
  top: 62.964999999999996px;
  position: absolute;
  animation: ldio-eeii88l764 linear 0.4854368932038836s infinite;
  background: #85a2b6;
  width: 25.7px;
  height: 28.27px;
  border-radius: 12.85px / 14.135px;
  transform-origin: 12.85px 65.535px;
}
.ldio-eeii88l764 div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -0.4368932038834953s;
  background: #85a2b6;
}
.ldio-eeii88l764 div:nth-child(2) {
  transform: rotate(36deg);
  animation-delay: -0.3883495145631069s;
  background: #85a2b6;
}
.ldio-eeii88l764 div:nth-child(3) {
  transform: rotate(72deg);
  animation-delay: -0.3398058252427185s;
  background: #85a2b6;
}
.ldio-eeii88l764 div:nth-child(4) {
  transform: rotate(108deg);
  animation-delay: -0.2912621359223302s;
  background: #85a2b6;
}
.ldio-eeii88l764 div:nth-child(5) {
  transform: rotate(144deg);
  animation-delay: -0.2427184466019418s;
  background: #85a2b6;
}
.ldio-eeii88l764 div:nth-child(6) {
  transform: rotate(180deg);
  animation-delay: -0.19417475728155345s;
  background: #85a2b6;
}
.ldio-eeii88l764 div:nth-child(7) {
  transform: rotate(216deg);
  animation-delay: -0.1456310679611651s;
  background: #85a2b6;
}
.ldio-eeii88l764 div:nth-child(8) {
  transform: rotate(252deg);
  animation-delay: -0.09708737864077673s;
  background: #85a2b6;
}
.ldio-eeii88l764 div:nth-child(9) {
  transform: rotate(288deg);
  animation-delay: -0.04854368932038836s;
  background: #85a2b6;
}
.ldio-eeii88l764 div:nth-child(10) {
  transform: rotate(324deg);
  animation-delay: 0s;
  background: #85a2b6;
}
.loadingio-spinner-spinner-ce8pfm4ddfb {
  width: 257px;
  height: 257px;
  display: inline-block;
  overflow: hidden;
}
.ldio-eeii88l764 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-eeii88l764 div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>